from core.publications.objects_constants.flats import FLAT_BUILDING_TYPES, \
	FLAT_TYPES, FLAT_ROOMS_PLANNINGS


APARTMENTS_BUILDINGS_TYPES = FLAT_BUILDING_TYPES
APARTMENTS_FLAT_TYPES = FLAT_TYPES
APARTMENTS_ROOMS_PLANNING_TYPES = FLAT_ROOMS_PLANNINGS
